{
  "formatVersion": "1.1",
  "component": {
    "group": "org.example.aop",
    "module": "aop",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aop-1.0.jar",
          "url": "aop-1.0.jar",
          "size": 13052,
          "sha512": "f7823e4a29d098b95f3791b1485e1fe275ec16f4666da793dc1e43b7612d0a1a6e1567b8943da3cbe2382b9cf1d046451fd4771523ee3a38a94fb65fa27b21f2",
          "sha256": "def9905f608d1ec90dc96caa44bd8b1d43f3e5aec3d2fd976f7e2e3b55bfe4df",
          "sha1": "98d168db2312920ccbb72c168506c4b3f8f20801",
          "md5": "04e71808acf8d609ffee36017f82a052"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.20.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "aop-1.0.jar",
          "url": "aop-1.0.jar",
          "size": 13052,
          "sha512": "f7823e4a29d098b95f3791b1485e1fe275ec16f4666da793dc1e43b7612d0a1a6e1567b8943da3cbe2382b9cf1d046451fd4771523ee3a38a94fb65fa27b21f2",
          "sha256": "def9905f608d1ec90dc96caa44bd8b1d43f3e5aec3d2fd976f7e2e3b55bfe4df",
          "sha1": "98d168db2312920ccbb72c168506c4b3f8f20801",
          "md5": "04e71808acf8d609ffee36017f82a052"
        }
      ]
    }
  ]
}
